// Generated by insterra

variable "aws_secret_key" {}
variable "aws_region" {}
variable "aws_access_key" {}
provider "aws" {
  access_key = var.aws_access_key
  region     = var.aws_region
  secret_key = var.aws_secret_key
}

variable "instellar_host" {}
variable "instellar_auth_token" {}
provider "instellar" {
  auth_token = var.instellar_auth_token
  host       = var.instellar_host
}
