// Generated by insterra

module "instellar_link_sombrero_emg" {
  source  = "upmaru/bootstrap/instellar//modules/service"
  version = "0.6.3"

  certificate = module.aws_database_sombrero_cwi.certificate_url
  channels    = ["main", "master", "develop"]
  cluster_ids = [
    module.instellar_link_sombrero_scz.cluster_id
  ]
  credential = {
    host     = module.aws_database_sombrero_cwi.address
    password = module.aws_database_sombrero_cwi.password
    port     = module.aws_database_sombrero_cwi.port
    resource = module.aws_database_sombrero_cwi.db_name
    username = module.aws_database_sombrero_cwi.username
    secure   = true
  }

  driver                = "database/postgresql"
  driver_version        = module.aws_database_sombrero_cwi.engine_version
  insterra_component_id = 66
  provider_name         = "aws"
  slug                  = module.aws_database_sombrero_cwi.identifier
}

module "instellar_link_sombrero_scz" {
  source  = "upmaru/bootstrap/instellar"
  version = "0.6.3"

  bootstrap_node        = module.aws_compute_sombrero_hjt.bootstrap_node
  cluster_address       = module.aws_compute_sombrero_hjt.cluster_address
  cluster_name          = module.aws_compute_sombrero_hjt.identifier
  insterra_component_id = 67
  kit_slug              = "lite"
  nodes                 = module.aws_compute_sombrero_hjt.nodes
  password_token        = module.aws_compute_sombrero_hjt.trust_token
  provider_name         = "aws"
  region                = var.aws_region

}

module "instellar_link_polaris_dux" {
  source  = "upmaru/bootstrap/instellar//modules/service"
  version = "0.6.3"


  channels = ["main", "master", "develop"]
  cluster_ids = [
    module.instellar_link_sombrero_scz.cluster_id
  ]
  credential = {
    host     = module.aws_bucket_polaris_wvy.host
    password = module.aws_bucket_polaris_wvy.secret_access_key
    port     = module.aws_bucket_polaris_wvy.port
    resource = module.aws_bucket_polaris_wvy.region
    username = module.aws_bucket_polaris_wvy.access_key_id
    secure   = true
  }

  driver                = "bucket/aws-s3"
  driver_version        = module.aws_bucket_polaris_wvy.version
  insterra_component_id = 71
  provider_name         = "aws"
  slug                  = module.aws_bucket_polaris_wvy.identifier
}
